# Project_3_Data Cleaning_Cyberbullying in social media

## Part 1: Upload the data

### Libraries
Pandas and numpy will be needed for the analysis of the data.

In [1]:
import pandas as pd
import numpy as np

### Import data
Import the data from the .csv file provided and assign it to a variable named data

In [2]:
data = pd.read_csv('cyberbullying_in_social_media.xlsx-compherensive_cyberbullying_dat.csv')

## Part 2: Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any potential issues. Some of the things we are interested in identifying in the data at this stage include:

- Missing values, Special characters, Incorrect values, Extreme values or outliers, Duplicate records, Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand.

Let's see how the data looks by using pandas methods like head(), info()

In [3]:
data.head(5)

,Id,Text,IsRetweet,IsSelfMentioned,Retweets#,Favorites#,Hashtags#,Medias#,Mentions#,SenderId,...,Punctuations#,UpperCaseLetter#,Letter#,Symbols#,Words#,TWords#,UWords#,SlangWords#,AvgWordLength,IsCyberbullying
0,1.123850e+18,bir adam yanÄ±nda Ã§ocuklaÅŸan kadÄ±nÄ± fazlad...,False,False,59.0,1045,1,0,0,1.935601e+09,...,9,5,144,0,23,5,0,0,6.0,False
1,1.161960e+18,maÄŸlup mu desem mahcup mu ama ikisi de deÄŸil...,False,False,3.0,157,1,0,0,1.935601e+09,...,8,8,147,0,31,8,0,1,4.0,False
2,1.162600e+18,gÃ¼naydÄ±n iyi pazarlar allah acil ÅŸifalar ve...,False,False,1.0,3,0,0,11,9.276140e+17,...,0,2,64,2,12,2,0,0,5.0,False
3,1.163020e+18,ve ahmet arif leyla sÄ±na seslenir sevdiÄŸim Ã...,False,False,13.0,220,2,0,0,1.935601e+09,...,19,16,150,0,23,14,0,0,6.0,False
4,1.157730e+18,arkadaki sanal gerzek oyunun oynuyor,False,False,950.0,12104,0,1,0,4.495931e+06,...,0,1,35,0,5,1,0,1,7.0,False


This first 5 rows of the dataset doesn't tell us much about the data that we have, but we can have a first look at the features (columns) and some of the values that each one takes with .info().

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  5000 non-null   float64
 1   Text                5000 non-null   object
 2   IsRetweet           4995 non-null   object
 3   IsSelfMentioned     4994 non-null   object
 4   Retweets#           4967 non-null   float64
 5   Favorites#          5000 non-null   int64
 6   Hashtags#           5000 non-null   int64
 7   Medias#             5000 non-null   int64
 8   Mentions#           5000 non-null   int64
 9   SenderId            5000 non-null   float64
 10  SenderAccountYears  5000 non-null   int64
 11  SenderFavorites#    5000 non-null   int64
 12  SenderFollowings#   5000 non-null   int64
 13  SenderFollowers#    4995 non-null   float64
 14  SenderStatues#      5000 non-null   int64
 15  SenderLocation      4636 non-null   object
 16  Emojis#             4994 non-null   float64
 17  Punctuations#       5000 non-null   int64
 18  UpperCaseLetter#    5000 non-null   int64
 19  Letter#             5000 non-null   int64
 20  Symbols#            5000 non-null   int64
 21  Words#              5000 non-null   int64
 22  TWords#             5000 non-null   int64
 23  UWords#             5000 non-null   int64
 24  SlangWords#         5000 non-null   int64
 25  AvgWordLength       4830 non-null   float64
 26  IsCyberbullying     5000 non-null   bool
dtypes: bool(1), float64(6), int64(16), object(4)
memory usage: 1020.6+ KB

With the .info() method, we know which columns have missing values and the data types for each column.

In [5]:
data.describe()

,Id,Retweets#,Favorites#,Hashtags#,Medias#,Mentions#,SenderId,SenderAccountYears,SenderFavorites#,SenderFollowings#,...,Emojis#,Punctuations#,UpperCaseLetter#,Letter#,Symbols#,Words#,TWords#,UWords#,SlangWords#,AvgWordLength
count,5.000000e+03,4967.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5.000000e+03,...,4994.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,4830.000000
mean,1.149113e+18,132.104490,733.077400,0.203200,0.283400,0.561400,5.626014e+17,5.342000,20832.553400,6.714929e+03,...,0.396476,2.527800,4.274000,83.166200,0.082600,14.071000,2.687200,0.351800,0.780800,5.537474
std,8.370279e+16,1078.051319,4955.513189,0.932139,0.654194,1.654804,5.140665e+17,59.556367,53253.035314,6.511099e+04,...,1.683259,4.033123,10.682254,62.526913,0.474787,10.470028,3.638407,1.749242,0.914176,1.460512
min,1.292782e+09,0.000000,0.000000,0.000000,0.000000,0.000000,3.696241e+06,0.000000,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.158140e+18,0.000000,0.000000,0.000000,0.000000,0.000000,1.208505e+09,1.000000,575.250000,9.700000e+01,...,0.000000,0.000000,1.000000,35.000000,0.000000,6.000000,1.000000,0.000000,0.000000,5.000000
50%,1.159270e+18,0.000000,1.000000,0.000000,0.000000,0.000000,8.028470e+17,3.000000,3871.000000,2.970000e+02,...,0.000000,1.000000,1.000000,63.000000,0.000000,11.000000,1.000000,0.000000,1.000000,5.000000
75%,1.162010e+18,7.000000,44.000000,0.000000,0.000000,1.000000,1.067080e+18,6.000000,16760.250000,9.550000e+02,...,0.000000,4.000000,4.000000,116.000000,0.000000,20.000000,3.000000,0.000000,1.000000,6.000000
max,1.207300e+18,29086.000000,163984.000000,23.000000,4.000000,50.000000,1.207070e+18,2020.000000,814597.000000,1.658816e+06,...,55.000000,84.000000,239.000000,249.000000,8.000000,49.000000,40.000000,40.000000,7.000000,53.000000

### Missing value

Let's see how prevalent missing values are in our data. We can use the Pandas isnull method to check whether the value in each field is missing (null) and return either True or False for each field. We can use the sum method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

In [6]:
null_cols = data.isnull().sum()
null_cols[null_cols > 0]

IsRetweet             5
IsSelfMentioned       6
Retweets#            33
SenderFollowers#      5
SenderLocation      364
Emojis#               6
AvgWordLength       170
dtype: int64

## Part 3: Data cleansing (missing values, outliers, duplicates, data consistently)

### 1. Filling missing value for the numerical columns.

In [7]:
# Count the frequency of all elements in the columns "Retweets#"
data["Retweets#"].value_counts()

0.0       2862
1.0        412
2.0        149
3.0        103
4.0         65
          ...
836.0        1
950.0        1
2375.0       1
113.0        1
8220.0       1
Name: Retweets#, Length: 471, dtype: int64

In [8]:
## Remplace missing values in the columns "Retweets#" by 0 because 0 is the most frequency (2862 times)

data["Retweets#"].fillna((0), inplace=True)

## Remplace missing values by mean() for the other numeric columns

data["SenderFollowers#"].fillna(value=data["SenderFollowers#"].mean(), inplace=True)
data["AvgWordLength"].fillna(value=data["AvgWordLength"].mean(), inplace=True)
data["Emojis#"].fillna(value=data["Emojis#"].mean(), inplace=True)
data["AvgWordLength"].fillna(value=data["AvgWordLength"].mean(), inplace=True)

### 2. Normalize the type of the columns

In [9]:
#Changing type of the data of the IsRetweet & IsSelfMentioned columns to booleans :

data['IsRetweet'] = data['IsRetweet'].astype('bool')
data['IsSelfMentioned'] = data['IsSelfMentioned'].astype('bool')

In [10]:
#Changing the columns with the type of data float to int :

data['Id'] = data['Id'].astype('int64')
data['Retweets#'] = data['Retweets#'].astype('int64')
data['SenderId'] = data['SenderId'].astype('int64')
data['SenderFollowers#'] = data['SenderFollowers#'].astype('int64')
data['Emojis#'] = data['Emojis#'].astype('int64')
data['AvgWordLength'] = data['AvgWordLength'].astype('int64')

### 3. Finding and Removing Duplicates

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. Pandas provides us with the ability to do that via the drop_duplicates method. We will use the len method to calculate the number of rows in the data set both before and after removing duplicates and then print the number of rows dropped.

In [11]:
before = len(data)
data = data.drop_duplicates()
after = len(data)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  2

### 4. Removing low variance column

We will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

In [12]:
## Find the columns with low variance

low_variance = []

for col in data._get_numeric_data():
    minimum = min(data[col])
    ninety_perc = np.percentile(data[col], 90)
    if ninety_perc == minimum:
        low_variance.append(col)

print(low_variance)

['IsRetweet', 'IsSelfMentioned', 'Symbols#']

In [13]:
## drop the low varaiance columns
data = data.drop(low_variance, axis=1)

### 5. Removing the unless column

In [14]:
## find all columns of the data

data.columns

Index(['Id', 'Text', 'Retweets#', 'Favorites#', 'Hashtags#', 'Medias#',
       'Mentions#', 'SenderId', 'SenderAccountYears', 'SenderFavorites#',
       'SenderFollowings#', 'SenderFollowers#', 'SenderStatues#',
       'SenderLocation', 'Emojis#', 'Punctuations#', 'UpperCaseLetter#',
       'Letter#', 'Words#', 'TWords#', 'UWords#', 'SlangWords#',
       'AvgWordLength', 'IsCyberbullying'],
      dtype='object')

In [18]:
## Removing the unless columns

unless_column=['Text','SenderAccountYears','Emojis#', 'Punctuations#',
       'UpperCaseLetter#', 'TWords#',
       'UWords#', 'SlangWords#','SenderLocation']
data = data.drop(unless_column, axis=1)

### 6. Extreme Values and Outliers

We should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

In [19]:
def find_outliers_by_decile(data, columns):
    outliers = pd.DataFrame(columns=data.columns)
    
    for col in columns:
        lower_decile = data[col].quantile(0.1)
        upper_decile = data[col].quantile(0.9)
        results = data[(data[col] < lower_decile) | (data[col] > upper_decile)].copy()
        results['Outlier'] = col
        outliers = outliers.append(results)
        
    return outliers

## Find the outlier for only 2 columns 'Retweets#','Favorites#'

outliers = find_outliers_by_decile(data, columns=['Retweets#','Favorites#'])

In [20]:
outliers

,Id,Retweets#,Favorites#,Hashtags#,Medias#,Mentions#,SenderId,SenderFavorites#,SenderFollowings#,SenderFollowers#,SenderStatues#,Letter#,Words#,AvgWordLength,IsCyberbullying,Outlier
4,1157730000000000000,950,12104,0,1,0,4495931,22554,32766,60281,25482,35,5,7,False,Retweets#
10,1292782403,678,1761,0,0,0,23186079,67,71,8631496,72643,104,15,6,False,Retweets#
11,22888045074,10464,19727,0,0,0,33536404,691,738,273849,7923,90,16,5,False,Retweets#
13,25485200000000000,303,386,0,0,0,23186079,67,71,8631496,72643,117,20,5,False,Retweets#
15,81419000000000000,1064,1692,1,0,0,23186079,67,71,8631496,72643,115,18,6,False,Retweets#
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4015,1158230000000000000,578,3246,1,1,0,1122480000000000000,0,0,9513,103,84,11,7,False,Favorites#
4031,1158380000000000000,234,3531,0,0,0,1115000000000000000,93,0,56484,1365,39,7,5,False,Favorites#
4187,1158680000000000000,49,11685,1,1,0,1140350000000000000,2237,87,64,801,41,10,4,False,Favorites#
4299,1159350000000000000,146,1501,0,0,0,1083280000000000000,43,2,27939,597,53,8,6,True,Favorites#
4766,1163160000000000000,34,1024,0,0,0,1081600000000000000,564549,14881,16362,551,69,14,4,False,Favorites#

"find_outliers_by_decile" is considering data points that are outside of the 10th and 90th percentile of each column as outliers. In this case, the function is only looking at the columns Retweets# and Favorites#, so the number of outliers is the total number of data points in these columns that fall outside of the 10th and 90th percentile.
The result of outlier have 999 rows, it's about 20% of the data. So in this case, we don't drop the outliers.

In [22]:
data.columns = data.columns.str.replace('#', '')

In [23]:
data.columns

Index(['Id', 'Retweets', 'Favorites', 'Hashtags', 'Medias', 'Mentions',
       'SenderId', 'SenderFavorites', 'SenderFollowings', 'SenderFollowers',
       'SenderStatues', 'Letter', 'Words', 'AvgWordLength', 'IsCyberbullying'],
      dtype='object')

## Part 4 : Export the Data to a CSV file

In [24]:
data.to_csv('project_3.csv',index=None)